apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctc-rcs-op
spec:
  selector:
    matchLabels:
      app: ctc-rcs-op-server
  replicas: 2
  template:
    metadata:
      labels:
        app: ctc-rcs-op-server
    spec:
      containers:
      - name: ctc-rcs-op-server
        image: nginx:latest
        ports:
        - containerPort: 80
